export const PROD_PANEL_KEY = 'PROD_PANEL'
export const COUNT_PANEL_KEY = 'COUNT_PANEL'
export const SCHOOL_PANEL_KEY = 'SCHOOL_PANEL'
const CART_DISCARD = 'CART_DISCARD'
const CART_PUT = 'CART_PUT'
const CART_CLEAR = 'CART_CLEAR'
const CART_SUBMIT = 'CART_SUBMIT'

export const PAGE_MAX_PURCHASES = 5

export const FOOTER_BUTTONS = [
    CART_PUT,
    CART_DISCARD,
    CART_CLEAR,
    CART_SUBMIT
]
